spring:
  main:
    banner-mode: 'off'
  profiles: test
  datasource:
    driver-class-name: org.h2.Driver
    url: jdbc:h2:mem:db;DB_CLOSE_DELAY=-1;INIT=CREATE SCHEMA IF NOT EXISTS SHOPINGCART
    username: admin
    password: admin
  jpa:
    properties:
      hibernate:
        default_schema: SHOPINGCART
        ddl-auto: none
logging:
  pattern:
    console: '%msg%n'
  level:
    org.springframework: info,error,debug